import { z } from "zod";
import type { ToolRegistry } from "../../application/tool/registry.js";
import { zodToLuauType } from "../../application/services/zod-luau-type.js";
import { describeInputFields } from "../../application/services/schema-introspect.js";
import { buildToolGuidance } from "../../application/services/tool-definition-quality.js";

function kebabToCamel(s: string): string {
  return s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

/**
 * Emit a full `mcp.d.luau` declaration from the live tool registry. The result
 * is consumable by Luau LSP — operators can drop it next to their scripts and
 * get autocomplete + hover on `mcp.<tool>(args)` everywhere, not just in the
 * in-browser REPL.
 *
 * Each tool's input Zod schema is converted to a Luau type alias; the `mcp`
 * table is then declared as a record of `(args: <Input>?) -> any` callables.
 */
export function emitMcpLuauTypes(registry: ToolRegistry): string {
  const tools = registry
    .list()
    .slice()
    .sort((a, b) => a.name.localeCompare(b.name));

  const aliasLines: string[] = [];
  const methodLines: string[] = [];

  for (const tool of tools) {
    const aliasName =
      "Mcp_" + kebabToCamel(tool.name).replace(/^([a-z])/, (m) => m.toUpperCase()) + "Input";
    const guidance = buildToolGuidance(tool);
    const fields = describeInputFields(tool.input);
    // For object inputs, emit a structured alias whose fields each carry their
    // own `-- description` comment so Luau LSPs hover-render the docstring per
    // argument. For non-object inputs, fall back to the compact one-shot type.
    let typeBody: string;
    if (tool.input instanceof z.ZodObject) {
      if (fields.length === 0) {
        typeBody = "{}";
      } else {
        const lines: string[] = ["{"];
        for (const field of fields) {
          if (field.description) {
            const oneLine = field.description.replace(/\s+/g, " ").trim();
            const trimmed = oneLine.length > 200 ? oneLine.slice(0, 197) + "..." : oneLine;
            lines.push(`    -- ${trimmed}`);
          }
          if (field.constraints.length > 0) {
            lines.push(`    -- Constraints: ${field.constraints.join("; ").slice(0, 220)}`);
          }
          if (field.defaultValue !== undefined) {
            lines.push(`    -- Default: ${JSON.stringify(field.defaultValue).slice(0, 160)}`);
          }
          lines.push(`    -- Example: ${JSON.stringify(field.example).slice(0, 160)}`);
          lines.push(`    ${field.name}: ${field.type},`);
        }
        lines.push("  }");
        typeBody = lines.join("\n  ");
      }
    } else {
      try {
        typeBody = zodToLuauType(tool.input);
      } catch {
        typeBody = "{[string]: any}";
      }
    }
    aliasLines.push(`-- ${tool.title}`);
    aliasLines.push(
      `-- Phase: ${guidance.execution.phase}; cost: ${guidance.execution.estimatedCost}; quality: ${guidance.quality.grade} (${guidance.quality.score})`,
    );
    if (tool.description) {
      const oneLine = tool.description.replace(/\s+/g, " ").trim();
      const trimmed = oneLine.length > 220 ? oneLine.slice(0, 217) + "..." : oneLine;
      aliasLines.push(`-- ${trimmed}`);
    }
    aliasLines.push(`export type ${aliasName} = ${typeBody}`);
    aliasLines.push("");

    const camel = kebabToCamel(tool.name);
    const argsType = guidance.requiredInputs.length > 0 ? aliasName : `${aliasName}?`;
    methodLines.push(`  ${camel}: (args: ${argsType}) -> any,`);
  }

  return [
    "--!strict",
    "-- mcp.d.luau",
    "-- AUTO-GENERATED by the executor-mcp dashboard. Do not hand-edit.",
    `-- ${tools.length} tools across ${registry.categoryCounts().length} categories.`,
    "",
    aliasLines.join("\n"),
    "export type McpDeferred = { __mcpDeferred: boolean, tool: string, args: any }",
    "",
    "declare mcp: {",
    methodLines.join("\n"),
    "  -- Lower-level call by kebab name (when you have it as a string).",
    "  call: (name: string, args: any?) -> any,",
    "  -- Run multiple calls in parallel server-side via one rpc-batch frame.",
    "  -- spec entries can be { tool, args } / { tool=, args= } / a string tool",
    "  -- name / an McpDeferred from mcp.defer.",
    "  all: (spec: {[any]: any}) -> {[any]: any},",
    "  -- Alias for mcp.all.",
    "  parallel: (spec: {[any]: any}) -> {[any]: any},",
    "  -- Build a deferred call descriptor for use inside mcp.parallel/mcp.all.",
    "  defer: (name: string, args: any?) -> McpDeferred,",
    "  -- Publish to a cross-game channel; subscribers in any connected script receive it.",
    "  publish: (channel: string, payload: any?) -> any,",
    "  -- Subscribe to a cross-game channel; handler receives (payload, fromClientId).",
    "  subscribe: (channel: string, handler: (any, string) -> ()) -> any,",
    "  -- Look up a tool's input schema + Luau signature at runtime. With no name,",
    "  -- returns every tool's signature. Use this BEFORE calling an unfamiliar tool.",
    "  help: (name: string?) -> any,",
    "}",
    "",
    "return mcp",
    "",
  ].join("\n");
}
